### ISSUE TITLE
need to support Nodejs 16 

### ISSUE THREAD

**Issue by jaredwray** [douglascayers/promise-coalesce#11]
@douglascayers - We are still supporting nodejs 16 in cache-manager. Would you be willing to fix it on your side or I will have to swap it out with something different.

**Comment by douglascayers** [comment]
Sorry about that! I don't think this package is using any 18+ features so hopefully it's a simple "engines" fix in the package.json

I'll test as soon as I'm back to a computer tonight.

**Comment by jaredwray** [comment]
Thanks @douglascayers - we will be moving off of `v16` in the next 6 months as it is clear but will need to do a major version bump at that point.
